version: '3.8'

services:
  db:
    build: db
    restart: always
    volumes:
      - ./db/mysql:/var/lib/mysql
    ports:
      - '3307:3306'
    container_name: mirea_rschir_database
  apache:
    restart: always
    build: apache
    ports:
      - '8080:8080'
    container_name: mirea_rschir_apache
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/static-content:/usr/share/nginx/html
    container_name: mirea_rschir_nginx