CREATE DATABASE IF NOT EXISTS appDB;
CREATE USER IF NOT EXISTS 'user'@'%' IDENTIFIED BY 'password';
GRANT SELECT,UPDATE,INSERT,DELETE ON appDB.* TO 'user'@'%';
FLUSH PRIVILEGES;

USE appDB;
CREATE TABLE IF NOT EXISTS teachers (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  namee VARCHAR(20) NOT NULL,
  experience REAL NOT NULL,
  PRIMARY KEY (ID)
);
CREATE TABLE IF NOT EXISTS students (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  namee VARCHAR(20) NOT NULL,
  averageMark REAL NOT NULL,
  tutorId INT(11),
  PRIMARY KEY (ID),
  FOREIGN KEY (tutorId) REFERENCES teachers (ID)
);
